{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- include "dashboard-application.metadata" . | nindent 2 }}
spec:
  selector:
    {{- include "dashboard-application.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.name }}
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- end }}